In [1]:
from datascience import *

In [2]:
Table()  # empty table

In [3]:
Table().with_column('Name', make_array('Lawton', 'Lonzo', 'Bill'))

Name
Lawton
Lonzo
Bill

In [4]:
Table().with_columns(
    'Name', make_array('Lawton', 'Lonzo', 'Bill'),
    'Age',  make_array(32, 5, 33)
)

Name   | Age
Lawton | 32
Lonzo  | 5
Bill   | 33

In [5]:
people = Table().with_columns(
    'Name', make_array('Lawton', 'Lonzo', 'Bill'),
    'Age',  make_array(32, 5, 33)
)

In [6]:
people

Name   | Age
Lawton | 32
Lonzo  | 5
Bill   | 33

In [7]:
# It's fine to use the plural with_columns and only add a single column
people.with_columns('Employer', make_array("CCC", 'Unemployed', 'CCC'))

Name   | Age  | Employer
Lawton | 32   | CCC
Lonzo  | 5    | Unemployed
Bill   | 33   | CCC

In [8]:
people  # didn't change

Name   | Age
Lawton | 32
Lonzo  | 5
Bill   | 33

In [9]:
people.relabeled('Age', 'Trips around the sun')

Name   | Trips around the sun
Lawton | 32
Lonzo  | 5
Bill   | 33

In [10]:
people

Name   | Age
Lawton | 32
Lonzo  | 5
Bill   | 33

---

In [11]:
cones = Table.read_table('data/cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
vanilla    | white       | 3.5
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [12]:
cones.num_columns

3

In [13]:
cones.num_rows

7

In [14]:
cones.labels

('Flavor', 'Color', 'Price')

In [15]:
cones.column('Price')

array([ 3.55,  4.75,  5.25,  3.5 ,  5.25,  5.25,  4.75])

In [16]:
cones.column(2)

array([ 3.55,  4.75,  5.25,  3.5 ,  5.25,  5.25,  4.75])

In [17]:
cones.column('Price').item(3)

3.5

In [18]:
cones.column('Price').item(0)  # first one is at index 0

3.55

In [19]:
# crushed ice: calculate the total price after applying 8.75% sales tax to the Price column

In [20]:
# option 1
tax = cones.column('Price') * .0875
tax + cones.column('Price')

array([ 3.860625,  5.165625,  5.709375,  3.80625 ,  5.709375,  5.709375,
        5.165625])

In [21]:
# option 2
import numpy as np
np.round(cones.column('Price') * 1.0875, 2)

array([ 3.86,  5.17,  5.71,  3.81,  5.71,  5.71,  5.17])

In [22]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
vanilla    | white       | 3.5
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [23]:
tax_rate = 0.0875
tax = cones.column('Price') * .0875
cones = cones.with_column('Price with tax', tax + cones.column('Price'))
cones

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | 3.86062
chocolate  | light brown | 4.75  | 5.16563
chocolate  | dark brown  | 5.25  | 5.70937
vanilla    | white       | 3.5   | 3.80625
strawberry | pink        | 5.25  | 5.70937
chocolate  | dark brown  | 5.25  | 5.70937
bubblegum  | pink        | 4.75  | 5.16563

In [24]:
cones.set_format('Price with tax', CurrencyFormatter)

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
bubblegum  | pink        | 4.75  | $5.17

In [25]:
Table().with_column('x', make_array(1000, 10000, 9999999999999)).set_format('x', NumberFormatter)

x
1,000
10,000
9,999,999,999,999

In [26]:
Table().with_column('x', make_array(0.5, 0.75, 0.9999)).set_format('x', PercentFormatter)

x
50.00%
75.00%
99.99%

In [27]:
cones

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
bubblegum  | pink        | 4.75  | $5.17

In [28]:
cones.select('Flavor', "Price with tax")

Flavor     | Price with tax
strawberry | $3.86
chocolate  | $5.17
chocolate  | $5.71
vanilla    | $3.81
strawberry | $5.71
chocolate  | $5.71
bubblegum  | $5.17

In [29]:
cones.select(0, 3)  # indices work too

Flavor     | Price with tax
strawberry | $3.86
chocolate  | $5.17
chocolate  | $5.71
vanilla    | $3.81
strawberry | $5.71
chocolate  | $5.71
bubblegum  | $5.17

In [30]:
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
vanilla
strawberry
chocolate
bubblegum

In [31]:
cones.column('Flavor') # only this one makes an array

array(['strawberry', 'chocolate', 'chocolate', 'vanilla', 'strawberry',
       'chocolate', 'bubblegum'],
      dtype='<U10')

In [33]:
cones.drop('Price')  # makes a new Table, as usual

Flavor     | Color       | Price with tax
strawberry | pink        | $3.86
chocolate  | light brown | $5.17
chocolate  | dark brown  | $5.71
vanilla    | white       | $3.81
strawberry | pink        | $5.71
chocolate  | dark brown  | $5.71
bubblegum  | pink        | $5.17

In [35]:
cones.sort('Price with tax')

Flavor     | Color       | Price | Price with tax
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
bubblegum  | pink        | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71

In [36]:
cones.sort('Price with tax', descending=True)

Flavor     | Color       | Price | Price with tax
chocolate  | dark brown  | 5.25  | $5.71
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
chocolate  | light brown | 4.75  | $5.17
bubblegum  | pink        | 4.75  | $5.17
strawberry | pink        | 3.55  | $3.86
vanilla    | white       | 3.5   | $3.81

In [37]:
cones

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
bubblegum  | pink        | 4.75  | $5.17

In [38]:
cones.take(4)

Flavor     | Color | Price | Price with tax
strawberry | pink  | 5.25  | $5.71

In [40]:
cones.take(1, 3, 5)

Flavor    | Color       | Price | Price with tax
chocolate | light brown | 4.75  | $5.17
vanilla   | white       | 3.5   | $3.81
chocolate | dark brown  | 5.25  | $5.71

In [44]:
import numpy as np
cones.take(np.arange(1, cones.num_rows, 2))  # all the odd indices

Flavor    | Color       | Price | Price with tax
chocolate | light brown | 4.75  | $5.17
vanilla   | white       | 3.5   | $3.81
chocolate | dark brown  | 5.25  | $5.71

In [45]:
cones

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
bubblegum  | pink        | 4.75  | $5.17

In [47]:
cones.where('Flavor', 'chocolate')  # by default, this is an equality check

Flavor    | Color       | Price | Price with tax
chocolate | light brown | 4.75  | $5.17
chocolate | dark brown  | 5.25  | $5.71
chocolate | dark brown  | 5.25  | $5.71

In [48]:
cones.where('Flavor', are.equal_to('chocolate'))  # the above is shorthand for this

Flavor    | Color       | Price | Price with tax
chocolate | light brown | 4.75  | $5.17
chocolate | dark brown  | 5.25  | $5.71
chocolate | dark brown  | 5.25  | $5.71

In [50]:
cones.where('Price with tax', are.below_or_equal_to(5))

Flavor     | Color | Price | Price with tax
strawberry | pink  | 3.55  | $3.86
vanilla    | white | 3.5   | $3.81

In [51]:
cones.where('Price with tax', are.below_or_equal_to(5)).sort('Price with tax')

Flavor     | Color | Price | Price with tax
vanilla    | white | 3.5   | $3.81
strawberry | pink  | 3.55  | $3.86

In [52]:
cones

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
bubblegum  | pink        | 4.75  | $5.17

In [53]:
cones.where('Color', are.containing('brown'))

Flavor    | Color       | Price | Price with tax
chocolate | light brown | 4.75  | $5.17
chocolate | dark brown  | 5.25  | $5.71
chocolate | dark brown  | 5.25  | $5.71

In [54]:
cones

Flavor     | Color       | Price | Price with tax
strawberry | pink        | 3.55  | $3.86
chocolate  | light brown | 4.75  | $5.17
chocolate  | dark brown  | 5.25  | $5.71
vanilla    | white       | 3.5   | $3.81
strawberry | pink        | 5.25  | $5.71
chocolate  | dark brown  | 5.25  | $5.71
bubblegum  | pink        | 4.75  | $5.17

In [55]:
cones.show(3)  # shows the first 3. .show() with nothing shows everything!

---

In [57]:
pokemon = Table.read_table('data/pokemon.csv')
pokemon

abilities                   | against_bug | against_dark | against_dragon | against_electric | against_fairy | against_fight | against_fire | against_flying | against_ghost | against_grass | against_ground | against_ice | against_normal | against_poison | against_psychic | against_rock | against_steel | against_water | attack | base_egg_steps | base_happiness | base_total | capture_rate | classfication       | defense | experience_growth | height_m | hp   | japanese_name    | name       | percentage_male | pokedex_number | sp_attack | sp_defense | speed | type1 | type2  | weight_kg | generation | is_legendary
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 49     | 5120           | 70             | 318        | 45           | Seed Pokémon        | 49      | 1059860           | 0.7      | 45   | Fushigidaneフシギダネ | Bulbasaur  | 88.1            | 1              | 65        | 65         | 45    | grass | poison | 6.9       | 1          | 0
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 62     | 5120           | 70             | 405        | 45           | Seed Pokémon        | 63      | 1059860           | 1        | 60   | Fushigisouフシギソウ  | Ivysaur    | 88.1            | 2              | 80        | 80         | 60    | grass | poison | 13        | 1          | 0
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 100    | 5120           | 70             | 625        | 45           | Seed Pokémon        | 123     | 1059860           | 2        | 80   | Fushigibanaフシギバナ | Venusaur   | 88.1            | 3              | 122       | 120        | 80    | grass | poison | 100       | 1          | 0
['Blaze', 'Solar Power']    | 0.5         | 1            | 1              | 1                | 0.5           | 1             | 0.5          | 1              | 1             | 0.5           | 2              | 0.5         | 1              | 1              | 1               | 2            | 0.5           | 2             | 52     | 5120           | 70             | 309        | 45           | Lizard Pokémon      | 43      | 1059860           | 0.6      | 39   | Hitokageヒトカゲ     | Charmander | 88.1            | 4              | 60        | 50         | 65    | fire  | nan    | 8.5       | 1          | 0
['Blaze', 'Solar Power']    | 0.5         | 1            | 1              | 1                | 0.5           | 1             | 0.5          | 1              | 1             | 0.5           | 2              | 0.5         | 1              | 1              | 1               | 2            | 0.5           | 2             | 64     | 5120           | 70             | 405        | 45           | Flame Pokémon       | 58      | 1059860           | 1.1      | 58   | Lizardoリザード      | Charmeleon | 88.1            | 5              | 80        | 65         | 80    | fire  | nan    | 19        | 1          | 0
['Blaze', 'Solar Power']    | 0.25        | 1            | 1              | 2                | 0.5           | 0.5           | 0.5          | 1              | 1             | 0.25          | 0              | 1           | 1              | 1              | 1               | 4            | 0.5           | 2             | 104    | 5120           | 70             | 634        | 45           | Flame Pokémon       | 78      | 1059860           | 1.7      | 78   | Lizardonリザードン    | Charizard  | 88.1            | 6              | 159       | 115        | 100   | fire  | flying | 90.5      | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 48     | 5120           | 70             | 314        | 45           | Tiny Turtle Pokémon | 65      | 1059860           | 0.5      | 44   | Zenigameゼニガメ     | Squirtle   | 88.1            | 7              | 50        | 64         | 43    | water | nan    | 9         | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 63     | 5120           | 70             | 405        | 45           | Turtle Pokémon      | 80      | 1059860           | 1        | 59   | Kameilカメール       | Wartortle  | 88.1            | 8              | 65        | 80         | 58    | water | nan    | 22.5      | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 103    | 5120           | 70             | 630        | 45           | Shellfish Pokémon   | 120     | 1059860           | 1.6      | 79   | Kamexカメックス       | Blastoise  | 88.1            | 9              | 135       | 115        | 78    | water | nan    | 85.5      | 1          | 0
['Shield Dust', 'Run Away'] | 1           | 1            | 1              | 1                | 1             | 0.5           | 2            | 2              | 1             | 0.5           | 0.5            | 1           | 1              | 1              | 1               | 2            | 1             | 1             | 30     | 3840           | 70             | 195        | 255          | Worm Pokémon        | 35      | 1000000           | 0.3      | 45   | Caterpieキャタピー    | Caterpie   | 50              | 10             | 20        | 20         | 45    | bug   | nan    | 2.9       | 1          | 0
... (791 rows omitted)

In [62]:
temp = pokemon.select('name', 'against_fire', 'type1')
temp

name       | against_fire | type1
Bulbasaur  | 2            | grass
Ivysaur    | 2            | grass
Venusaur   | 2            | grass
Charmander | 0.5          | fire
Charmeleon | 0.5          | fire
Charizard  | 0.5          | fire
Squirtle   | 0.5          | water
Wartortle  | 0.5          | water
Blastoise  | 0.5          | water
Caterpie   | 2            | bug
... (791 rows omitted)

In [64]:
temp.where('against_fire', are.equal_to(2))

name       | against_fire | type1
Bulbasaur  | 2            | grass
Ivysaur    | 2            | grass
Venusaur   | 2            | grass
Caterpie   | 2            | bug
Metapod    | 2            | bug
Butterfree | 2            | bug
Weedle     | 2            | bug
Kakuna     | 2            | bug
Beedrill   | 2            | bug
Oddish     | 2            | grass
... (177 rows omitted)

In [74]:
temp = pokemon.select('name', 'generation', 'speed', 'base_happiness')
temp

name       | generation | speed | base_happiness
Bulbasaur  | 1          | 45    | 70
Ivysaur    | 1          | 60    | 70
Venusaur   | 1          | 80    | 70
Charmander | 1          | 65    | 70
Charmeleon | 1          | 80    | 70
Charizard  | 1          | 100   | 70
Squirtle   | 1          | 43    | 70
Wartortle  | 1          | 58    | 70
Blastoise  | 1          | 78    | 70
Caterpie   | 1          | 45    | 70
... (791 rows omitted)

In [77]:
temp.where('generation', 2).sort('speed', descending=True).show(15)

In [80]:
temp.sort('base_happiness', descending=True).show(20)

In [82]:
temp = pokemon.select('name', 'against_poison')
temp

name       | against_poison
Bulbasaur  | 1
Ivysaur    | 1
Venusaur   | 1
Charmander | 1
Charmeleon | 1
Charizard  | 1
Squirtle   | 1
Wartortle  | 1
Blastoise  | 1
Caterpie   | 1
... (791 rows omitted)

In [85]:
temp.where('against_poison', are.below(1)).show(20)

In [86]:
pokemon

abilities                   | against_bug | against_dark | against_dragon | against_electric | against_fairy | against_fight | against_fire | against_flying | against_ghost | against_grass | against_ground | against_ice | against_normal | against_poison | against_psychic | against_rock | against_steel | against_water | attack | base_egg_steps | base_happiness | base_total | capture_rate | classfication       | defense | experience_growth | height_m | hp   | japanese_name    | name       | percentage_male | pokedex_number | sp_attack | sp_defense | speed | type1 | type2  | weight_kg | generation | is_legendary
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 49     | 5120           | 70             | 318        | 45           | Seed Pokémon        | 49      | 1059860           | 0.7      | 45   | Fushigidaneフシギダネ | Bulbasaur  | 88.1            | 1              | 65        | 65         | 45    | grass | poison | 6.9       | 1          | 0
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 62     | 5120           | 70             | 405        | 45           | Seed Pokémon        | 63      | 1059860           | 1        | 60   | Fushigisouフシギソウ  | Ivysaur    | 88.1            | 2              | 80        | 80         | 60    | grass | poison | 13        | 1          | 0
['Overgrow', 'Chlorophyll'] | 1           | 1            | 1              | 0.5              | 0.5           | 0.5           | 2            | 2              | 1             | 0.25          | 1              | 2           | 1              | 1              | 2               | 1            | 1             | 0.5           | 100    | 5120           | 70             | 625        | 45           | Seed Pokémon        | 123     | 1059860           | 2        | 80   | Fushigibanaフシギバナ | Venusaur   | 88.1            | 3              | 122       | 120        | 80    | grass | poison | 100       | 1          | 0
['Blaze', 'Solar Power']    | 0.5         | 1            | 1              | 1                | 0.5           | 1             | 0.5          | 1              | 1             | 0.5           | 2              | 0.5         | 1              | 1              | 1               | 2            | 0.5           | 2             | 52     | 5120           | 70             | 309        | 45           | Lizard Pokémon      | 43      | 1059860           | 0.6      | 39   | Hitokageヒトカゲ     | Charmander | 88.1            | 4              | 60        | 50         | 65    | fire  | nan    | 8.5       | 1          | 0
['Blaze', 'Solar Power']    | 0.5         | 1            | 1              | 1                | 0.5           | 1             | 0.5          | 1              | 1             | 0.5           | 2              | 0.5         | 1              | 1              | 1               | 2            | 0.5           | 2             | 64     | 5120           | 70             | 405        | 45           | Flame Pokémon       | 58      | 1059860           | 1.1      | 58   | Lizardoリザード      | Charmeleon | 88.1            | 5              | 80        | 65         | 80    | fire  | nan    | 19        | 1          | 0
['Blaze', 'Solar Power']    | 0.25        | 1            | 1              | 2                | 0.5           | 0.5           | 0.5          | 1              | 1             | 0.25          | 0              | 1           | 1              | 1              | 1               | 4            | 0.5           | 2             | 104    | 5120           | 70             | 634        | 45           | Flame Pokémon       | 78      | 1059860           | 1.7      | 78   | Lizardonリザードン    | Charizard  | 88.1            | 6              | 159       | 115        | 100   | fire  | flying | 90.5      | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 48     | 5120           | 70             | 314        | 45           | Tiny Turtle Pokémon | 65      | 1059860           | 0.5      | 44   | Zenigameゼニガメ     | Squirtle   | 88.1            | 7              | 50        | 64         | 43    | water | nan    | 9         | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 63     | 5120           | 70             | 405        | 45           | Turtle Pokémon      | 80      | 1059860           | 1        | 59   | Kameilカメール       | Wartortle  | 88.1            | 8              | 65        | 80         | 58    | water | nan    | 22.5      | 1          | 0
['Torrent', 'Rain Dish']    | 1           | 1            | 1              | 2                | 1             | 1             | 0.5          | 1              | 1             | 2             | 1              | 0.5         | 1              | 1              | 1               | 1            | 0.5           | 0.5           | 103    | 5120           | 70             | 630        | 45           | Shellfish Pokémon   | 120     | 1059860           | 1.6      | 79   | Kamexカメックス       | Blastoise  | 88.1            | 9              | 135       | 115        | 78    | water | nan    | 85.5      | 1          | 0
['Shield Dust', 'Run Away'] | 1           | 1            | 1              | 1                | 1             | 0.5           | 2            | 2              | 1             | 0.5           | 0.5            | 1           | 1              | 1              | 1               | 2            | 1             | 1             | 30     | 3840           | 70             | 195        | 255          | Worm Pokémon        | 35      | 1000000           | 0.3      | 45   | Caterpieキャタピー    | Caterpie   | 50              | 10             | 20        | 20         | 45    | bug   | nan    | 2.9       | 1          | 0
... (791 rows omitted)

In [88]:
# question: how does the speed of pokemon that are more likely to be female 
# compare to the speed of pokemon that are more likely to be male?
temp = pokemon.select('name', 'percentage_male', 'speed')
temp

name       | percentage_male | speed
Bulbasaur  | 88.1            | 45
Ivysaur    | 88.1            | 60
Venusaur   | 88.1            | 80
Charmander | 88.1            | 65
Charmeleon | 88.1            | 80
Charizard  | 88.1            | 100
Squirtle   | 88.1            | 43
Wartortle  | 88.1            | 58
Blastoise  | 88.1            | 78
Caterpie   | 50              | 45
... (791 rows omitted)

In [91]:
temp = temp.with_column('percentage_female', 100 - temp.column('percentage_male'))
temp

name       | percentage_male | speed | percentage_female
Bulbasaur  | 88.1            | 45    | 11.9
Ivysaur    | 88.1            | 60    | 11.9
Venusaur   | 88.1            | 80    | 11.9
Charmander | 88.1            | 65    | 11.9
Charmeleon | 88.1            | 80    | 11.9
Charizard  | 88.1            | 100   | 11.9
Squirtle   | 88.1            | 43    | 11.9
Wartortle  | 88.1            | 58    | 11.9
Blastoise  | 88.1            | 78    | 11.9
Caterpie   | 50              | 45    | 50
... (791 rows omitted)

In [99]:
temp.where('percentage_female', are.above(50)).num_rows

53

In [94]:
temp.where('percentage_female', are.above(50)).column('speed').mean()

66.79245283018868

In [101]:
temp.where('percentage_male', are.above(50)).num_rows

149

In [95]:
temp.where('percentage_male', are.above(50)).column('speed').mean()

68.953020134228183

In [106]:
temp = pokemon.select('name', 'type1', 'generation').relabeled('type1', 'type')
temp

name       | type  | generation
Bulbasaur  | grass | 1
Ivysaur    | grass | 1
Venusaur   | grass | 1
Charmander | fire  | 1
Charmeleon | fire  | 1
Charizard  | fire  | 1
Squirtle   | water | 1
Wartortle  | water | 1
Blastoise  | water | 1
Caterpie   | bug   | 1
... (791 rows omitted)

In [107]:
temp.where('type', 'electric').where('generation', are.equal_to(1))

name       | type     | generation
Pikachu    | electric | 1
Raichu     | electric | 1
Magnemite  | electric | 1
Magneton   | electric | 1
Voltorb    | electric | 1
Electrode  | electric | 1
Electabuzz | electric | 1
Jolteon    | electric | 1
Zapdos     | electric | 1

In [108]:
# please never do this, but this is kinda cool
Is = are
temp.where('type', 'electric').where('generation', Is.equal_to(1))

name       | type     | generation
Pikachu    | electric | 1
Raichu     | electric | 1
Magnemite  | electric | 1
Magneton   | electric | 1
Voltorb    | electric | 1
Electrode  | electric | 1
Electabuzz | electric | 1
Jolteon    | electric | 1
Zapdos     | electric | 1

In [111]:
pokemon.select('name', 'abilities').where('abilities', are.containing('Run Away')).show()

---

In [3]:
cereal = Table.read_table('data/cereal.csv')
cereal.show(15)

In [4]:
shelves = cereal.select('name', 'shelf', 'sugars')
shelves

name                      | shelf | sugars
100% Bran                 | 3     | 6
100% Natural Bran         | 3     | 8
All-Bran                  | 3     | 5
All-Bran with Extra Fiber | 3     | 0
Almond Delight            | 3     | 8
Apple Cinnamon Cheerios   | 1     | 10
Apple Jacks               | 2     | 14
Basic 4                   | 3     | 8
Bran Chex                 | 1     | 6
Bran Flakes               | 3     | 5
... (67 rows omitted)

In [7]:
shelf_1 = shelves.where('shelf', are.equal_to(1))
shelf_1

name                    | shelf | sugars
Apple Cinnamon Cheerios | 1     | 10
Bran Chex               | 1     | 6
Cheerios                | 1     | 1
Corn Chex               | 1     | 3
Corn Flakes             | 1     | 2
Frosted Flakes          | 1     | 11
Golden Crisp            | 1     | 15
Honey Nut Cheerios      | 1     | 10
Honey-comb              | 1     | 11
Multi-Grain Cheerios    | 1     | 6
... (10 rows omitted)

In [12]:
shelf_1.column('sugars').mean()

4.7999999999999998

In [15]:
shelves.where('shelf', are.equal_to(2)).column('sugars').mean()

9.6190476190476186

In [16]:
shelves.where('shelf', are.equal_to(3)).column('sugars').mean()

6.5277777777777777

In [20]:
cold_vs_hot = cereal.select('name', 'type', 'protein', 'fiber')
cold_vs_hot

name                      | type | protein | fiber
100% Bran                 | C    | 4       | 10
100% Natural Bran         | C    | 3       | 2
All-Bran                  | C    | 4       | 9
All-Bran with Extra Fiber | C    | 4       | 14
Almond Delight            | C    | 2       | 1
Apple Cinnamon Cheerios   | C    | 2       | 1.5
Apple Jacks               | C    | 2       | 1
Basic 4                   | C    | 3       | 2
Bran Chex                 | C    | 2       | 4
Bran Flakes               | C    | 3       | 5
... (67 rows omitted)

In [27]:
# what is the avg. amount of protein in the hot cereals in the dataset?
cold_vs_hot.where('type', are.equal_to('H')).column('protein').mean()

4.0

In [25]:
cold_vs_hot.where('type', are.equal_to('H')).column('fiber').mean()

1.2333333333333334

In [26]:
cold_vs_hot.where('type', 'C').column('protein').mean()

2.4864864864864864

In [28]:
cold_vs_hot.where('type', 'C').column('fiber').mean()

2.189189189189189

In [31]:
cereal.where('sugars', are.above(10)).sort('rating', descending=True)

name                              | mfr  | type | calories | protein | fat  | sodium | fiber | carbo | sugars | potass | vitamins | shelf | weight | cups | rating
Fruitful Bran                     | K    | C    | 120      | 3       | 0    | 240    | 5     | 14    | 12     | 190    | 25       | 3     | 1.33   | 0.67 | 41.0155
Raisin Bran                       | K    | C    | 120      | 3       | 1    | 210    | 5     | 14    | 12     | 240    | 25       | 2     | 1.33   | 0.75 | 39.2592
Post Nat. Raisin Bran             | P    | C    | 120      | 3       | 1    | 200    | 6     | 11    | 14     | 260    | 25       | 3     | 1.33   | 0.67 | 37.8406
Muesli Raisins; Dates; & Almonds  | R    | C    | 150      | 4       | 3    | 95     | 3     | 16    | 11     | 170    | 25       | 3     | 1      | 1    | 37.1369
Corn Pops                         | K    | C    | 110      | 1       | 0    | 90     | 1     | 13    | 12     | 20     | 25       | 2     | 1      | 1    | 35.7828
Golden Crisp                      | P    | C    | 100      | 2       | 0    | 45     | 0     | 11    | 15     | 40     | 25       | 1     | 1      | 0.88 | 35.2524
Muesli Raisins; Peaches; & Pecans | R    | C    | 150      | 4       | 3    | 150    | 3     | 16    | 11     | 170    | 25       | 3     | 1      | 1    | 34.1398
Apple Jacks                       | K    | C    | 110      | 2       | 0    | 125    | 1     | 11    | 14     | 30     | 25       | 2     | 1      | 1    | 33.1741
Froot Loops                       | K    | C    | 110      | 2       | 1    | 125    | 1     | 11    | 13     | 30     | 25       | 2     | 1      | 1    | 32.2076
Frosted Flakes                    | K    | C    | 110      | 1       | 0    | 200    | 1     | 14    | 11     | 25     | 25       | 1     | 1      | 0.75 | 31.436
... (11 rows omitted)

In [33]:
cereal.where('sugars', are.above(10)).column('rating').mean()

30.651622952380951

In [34]:
cereal.where('sugars', are.not_above(10)).column('rating').mean()

47.17098575

In [35]:
cereal.column('protein').mean()

2.5454545454545454

In [37]:
cereal.where('protein', are.below(2.5)).column('rating').mean()

37.26109794736842

In [38]:
cereal.where('protein', are.above_or_equal_to(2.5)).column('rating').mean()

47.931732358974365

In [39]:
cereal

name                      | mfr  | type | calories | protein | fat  | sodium | fiber | carbo | sugars | potass | vitamins | shelf | weight | cups | rating
100% Bran                 | N    | C    | 70       | 4       | 1    | 130    | 10    | 5     | 6      | 280    | 25       | 3     | 1      | 0.33 | 68.403
100% Natural Bran         | Q    | C    | 120      | 3       | 5    | 15     | 2     | 8     | 8      | 135    | 0        | 3     | 1      | 1    | 33.9837
All-Bran                  | K    | C    | 70       | 4       | 1    | 260    | 9     | 7     | 5      | 320    | 25       | 3     | 1      | 0.33 | 59.4255
All-Bran with Extra Fiber | K    | C    | 50       | 4       | 0    | 140    | 14    | 8     | 0      | 330    | 25       | 3     | 1      | 0.5  | 93.7049
Almond Delight            | R    | C    | 110      | 2       | 2    | 200    | 1     | 14    | 8      | -1     | 25       | 3     | 1      | 0.75 | 34.3848
Apple Cinnamon Cheerios   | G    | C    | 110      | 2       | 2    | 180    | 1.5   | 10.5  | 10     | 70     | 25       | 1     | 1      | 0.75 | 29.5095
Apple Jacks               | K    | C    | 110      | 2       | 0    | 125    | 1     | 11    | 14     | 30     | 25       | 2     | 1      | 1    | 33.1741
Basic 4                   | G    | C    | 130      | 3       | 2    | 210    | 2     | 18    | 8      | 100    | 25       | 3     | 1.33   | 0.75 | 37.0386
Bran Chex                 | R    | C    | 90       | 2       | 1    | 200    | 4     | 15    | 6      | 125    | 25       | 1     | 1      | 0.67 | 49.1203
Bran Flakes               | P    | C    | 90       | 3       | 0    | 210    | 5     | 13    | 5      | 190    | 25       | 3     | 1      | 0.67 | 53.3138
... (67 rows omitted)

In [44]:
vitamins_by_weight = cereal.column('vitamins') / cereal.column('weight')
vitamins_by_cups = cereal.column('vitamins') / cereal.column('cups')

In [47]:
vitamins = cereal.select('name', 'vitamins', 'weight', 'cups').with_columns(
    'vitamins by weight', vitamins_by_weight,
    'vitamins by cups', vitamins_by_cups
)
vitamins

name                      | vitamins | weight | cups | vitamins by weight | vitamins by cups
100% Bran                 | 25       | 1      | 0.33 | 25                 | 75.7576
100% Natural Bran         | 0        | 1      | 1    | 0                  | 0
All-Bran                  | 25       | 1      | 0.33 | 25                 | 75.7576
All-Bran with Extra Fiber | 25       | 1      | 0.5  | 25                 | 50
Almond Delight            | 25       | 1      | 0.75 | 25                 | 33.3333
Apple Cinnamon Cheerios   | 25       | 1      | 0.75 | 25                 | 33.3333
Apple Jacks               | 25       | 1      | 1    | 25                 | 25
Basic 4                   | 25       | 1.33   | 0.75 | 18.797             | 33.3333
Bran Chex                 | 25       | 1      | 0.67 | 25                 | 37.3134
Bran Flakes               | 25       | 1      | 0.67 | 25                 | 37.3134
... (67 rows omitted)

In [49]:
vitamins.sort('vitamins by weight', descending=True)

name                        | vitamins | weight | cups | vitamins by weight | vitamins by cups
Just Right Crunchy  Nuggets | 100      | 1      | 1    | 100                | 100
Product 19                  | 100      | 1      | 1    | 100                | 100
Total Corn Flakes           | 100      | 1      | 1    | 100                | 100
Total Whole Grain           | 100      | 1      | 1    | 100                | 100
Just Right Fruit & Nut      | 100      | 1.3    | 0.75 | 76.9231            | 133.333
Total Raisin Bran           | 100      | 1.5    | 1    | 66.6667            | 100
100% Bran                   | 25       | 1      | 0.33 | 25                 | 75.7576
All-Bran                    | 25       | 1      | 0.33 | 25                 | 75.7576
All-Bran with Extra Fiber   | 25       | 1      | 0.5  | 25                 | 50
Almond Delight              | 25       | 1      | 0.75 | 25                 | 33.3333
... (67 rows omitted)

In [50]:
vitamins.sort('vitamins by cups', descending=True)

name                        | vitamins | weight | cups | vitamins by weight | vitamins by cups
Just Right Fruit & Nut      | 100      | 1.3    | 0.75 | 76.9231            | 133.333
Grape-Nuts                  | 25       | 1      | 0.25 | 25                 | 100
Just Right Crunchy  Nuggets | 100      | 1      | 1    | 100                | 100
Product 19                  | 100      | 1      | 1    | 100                | 100
Total Corn Flakes           | 100      | 1      | 1    | 100                | 100
Total Raisin Bran           | 100      | 1.5    | 1    | 66.6667            | 100
Total Whole Grain           | 100      | 1      | 1    | 100                | 100
100% Bran                   | 25       | 1      | 0.33 | 25                 | 75.7576
All-Bran                    | 25       | 1      | 0.33 | 25                 | 75.7576
Great Grains Pecan          | 25       | 1      | 0.33 | 25                 | 75.7576
... (67 rows omitted)

In [84]:
titanic = Table.read_table('data/titanic.csv')
titanic

PassengerId | Survived | Pclass | Name                                                | Sex    | Age  | SibSp | Parch | Ticket           | Fare    | Cabin | Embarked
1           | 0        | 3      | Braund, Mr. Owen Harris                             | male   | 22   | 1     | 0     | A/5 21171        | 7.25    | nan   | S
2           | 1        | 1      | Cumings, Mrs. John Bradley (Florence Briggs Thayer) | female | 38   | 1     | 0     | PC 17599         | 71.2833 | C85   | C
3           | 1        | 3      | Heikkinen, Miss. Laina                              | female | 26   | 0     | 0     | STON/O2. 3101282 | 7.925   | nan   | S
4           | 1        | 1      | Futrelle, Mrs. Jacques Heath (Lily May Peel)        | female | 35   | 1     | 0     | 113803           | 53.1    | C123  | S
5           | 0        | 3      | Allen, Mr. William Henry                            | male   | 35   | 0     | 0     | 373450           | 8.05    | nan   | S
6           | 0        | 3      | Moran, Mr. James                                    | male   | nan  | 0     | 0     | 330877           | 8.4583  | nan   | Q
7           | 0        | 1      | McCarthy, Mr. Timothy J                             | male   | 54   | 0     | 0     | 17463            | 51.8625 | E46   | S
8           | 0        | 3      | Palsson, Master. Gosta Leonard                      | male   | 2    | 3     | 1     | 349909           | 21.075  | nan   | S
9           | 1        | 3      | Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   | female | 27   | 0     | 2     | 347742           | 11.1333 | nan   | S
10          | 1        | 2      | Nasser, Mrs. Nicholas (Adele Achem)                 | female | 14   | 1     | 0     | 237736           | 30.0708 | nan   | C
... (881 rows omitted)

In [85]:
titanic.column('Name').item(25).split(', ')

['Asplund', 'Mrs. Carl Oscar (Selma Augusta Emilia Johansson)']

In [86]:
titanic_no_nan_for_age = titanic.where('Age', are.above(0))
titanic_no_nan_for_age

PassengerId | Survived | Pclass | Name                                                | Sex    | Age  | SibSp | Parch | Ticket           | Fare    | Cabin | Embarked
1           | 0        | 3      | Braund, Mr. Owen Harris                             | male   | 22   | 1     | 0     | A/5 21171        | 7.25    | nan   | S
2           | 1        | 1      | Cumings, Mrs. John Bradley (Florence Briggs Thayer) | female | 38   | 1     | 0     | PC 17599         | 71.2833 | C85   | C
3           | 1        | 3      | Heikkinen, Miss. Laina                              | female | 26   | 0     | 0     | STON/O2. 3101282 | 7.925   | nan   | S
4           | 1        | 1      | Futrelle, Mrs. Jacques Heath (Lily May Peel)        | female | 35   | 1     | 0     | 113803           | 53.1    | C123  | S
5           | 0        | 3      | Allen, Mr. William Henry                            | male   | 35   | 0     | 0     | 373450           | 8.05    | nan   | S
7           | 0        | 1      | McCarthy, Mr. Timothy J                             | male   | 54   | 0     | 0     | 17463            | 51.8625 | E46   | S
8           | 0        | 3      | Palsson, Master. Gosta Leonard                      | male   | 2    | 3     | 1     | 349909           | 21.075  | nan   | S
9           | 1        | 3      | Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   | female | 27   | 0     | 2     | 347742           | 11.1333 | nan   | S
10          | 1        | 2      | Nasser, Mrs. Nicholas (Adele Achem)                 | female | 14   | 1     | 0     | 237736           | 30.0708 | nan   | C
11          | 1        | 3      | Sandstrom, Miss. Marguerite Rut                     | female | 4    | 1     | 1     | PP 9549          | 16.7    | G6    | S
... (704 rows omitted)

In [87]:
titanic_no_nan_for_age.where('Survived', 1).column('Age').mean()

28.343689655172415

In [88]:
titanic_no_nan_for_age.where('Survived', 0).column('Age').mean()

30.626179245283019

In [89]:
titanic_no_nan_for_fare = titanic.where('Fare', are.above(0))

In [90]:
titanic_no_nan_for_fare.where('Pclass', 1).column('Fare').mean()

86.148874407582937

In [91]:
titanic_no_nan_for_fare.where('Pclass', 2).column('Fare').mean()

21.358661235955054

In [92]:
titanic_no_nan_for_fare.where('Pclass', 3).column('Fare').mean()

13.7878749486653

In [93]:
titanic_no_nan_for_fare.column('Fare').mean()

32.755649885844747

In [94]:
titanic_no_nan_for_fare.where('Fare', are.above(20)).column('Survived').mean()

0.5292553191489362

In [95]:
titanic_no_nan_for_fare.where('Fare', are.not_above(20)).column('Survived').mean()

0.28399999999999997

In [96]:
titanic.where('Sex', 'male').column('Survived').mean()

0.18890814558058924

In [97]:
titanic.where('Sex', 'female').column('Survived').mean()

0.7420382165605095

In [101]:
titanic.where('Sex', 'male').where('Age', are.between_or_equal_to(18, 32)).where('Survived', 1).num_rows

39

In [102]:
titanic.where('Sex', 'female').where('Age', are.between_or_equal_to(18, 32)).where('Survived', 1).num_rows

83

In [103]:
temps = Table.read_table('data/max-min-temperatures-fresno-up-to-2025.csv')
temps

Date  | Highest High | Highest High Year | Lowest Low | Lowest Low Year
01/01 | 69           | 1998              | 21         | 1976
01/02 | 70           | 1948              | 20         | 1976
01/03 | 72           | 1948              | 23         | 1976
01/04 | 71           | 1948              | 22         | 1976
01/05 | 72           | 2018              | 20         | 1949
01/06 | 73           | 1948              | 17         | 1913
01/07 | 71           | 1911              | 20         | 1913
01/08 | 72           | 1911              | 22         | 1888
01/09 | 70           | 1953              | 23         | 1949
01/10 | 68           | 2025              | 18         | 1949
... (356 rows omitted)

In [108]:
temps.where('Date', are.containing('01/')).column('Lowest Low').mean()

22.0

In [109]:
import numpy as np

In [110]:
'hi' * 32

'hihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihi'

In [113]:
'#' * 70

'######################################################################'

In [117]:
widths = np.round(temps.column('Highest High') / 3).astype(int)
widths

array([23, 23, 24, 24, 24, 24, 24, 24, 23, 23, 25, 22, 23, 23, 25, 24, 25,
       23, 24, 24, 24, 23, 24, 26, 25, 24, 23, 26, 26, 25, 25, 24, 25, 26,
       26, 25, 25, 26, 25, 26, 25, 26, 27, 27, 26, 26, 27, 28, 28, 26, 27,
       26, 26, 26, 26, 27, 28, 26, 28, 26, 26, 27, 27, 28, 28, 29, 28, 28,
       29, 27, 29, 28, 28, 29, 30, 29, 30, 29, 29, 30, 29, 28, 30, 30, 30,
       29, 30, 28, 29, 30, 30, 30, 29, 30, 29, 31, 31, 31, 32, 32, 32, 32,
       32, 32, 33, 32, 32, 31, 32, 31, 32, 33, 32, 33, 34, 34, 33, 33, 33,
       32, 33, 34, 34, 33, 33, 33, 33, 34, 34, 34, 33, 33, 34, 34, 34, 34,
       34, 35, 34, 34, 34, 35, 35, 34, 34, 34, 34, 35, 36, 36, 36, 37, 35,
       35, 36, 35, 36, 36, 36, 36, 37, 35, 35, 36, 36, 36, 36, 37, 36, 37,
       37, 37, 37, 36, 36, 37, 37, 36, 37, 36, 37, 37, 38, 37, 37, 37, 37,
       37, 38, 38, 38, 37, 38, 37, 37, 37, 37, 37, 38, 37, 37, 37, 37, 37,
       38, 38, 38, 38, 38, 37, 38, 38, 38, 37, 37, 37, 37, 37, 37, 37, 38,
       37, 37, 38, 37, 37, 37, 36, 37, 37, 37, 37, 36, 36, 36, 37, 37, 37,
       36, 36, 36, 36, 36, 36, 36, 37, 37, 36, 36, 38, 37, 36, 36, 36, 37,
       35, 35, 35, 35, 35, 35, 36, 35, 35, 34, 35, 35, 34, 33, 36, 35, 35,
       34, 34, 33, 34, 35, 34, 34, 33, 33, 33, 33, 33, 32, 32, 32, 33, 33,
       32, 32, 32, 31, 31, 31, 31, 30, 32, 30, 30, 30, 30, 29, 30, 30, 29,
       29, 29, 29, 30, 29, 28, 28, 28, 28, 28, 27, 28, 26, 26, 27, 27, 27,
       28, 27, 27, 26, 26, 26, 25, 27, 26, 25, 25, 26, 25, 25, 25, 24, 24,
       26, 23, 26, 23, 25, 23, 23, 24, 25, 25, 23, 23, 24, 25, 23, 24, 23,
       23, 23, 24, 23, 24, 22, 23, 22, 23])

In [119]:
bars = np.char.multiply('#', widths)
bars

array(['#######################', '#######################',
       '########################', '########################',
       '########################', '########################',
       '########################', '########################',
       '#######################', '#######################',
       '#########################', '######################',
       '#######################', '#######################',
       '#########################', '########################',
       '#########################', '#######################',
       '########################', '########################',
       '########################', '#######################',
       '########################', '##########################',
       '#########################', '########################',
       '#######################', '##########################',
       '##########################', '#########################',
       '#########################', '########################',
       '#########################', '##########################',
       '##########################', '#########################',
       '#########################', '##########################',
       '#########################', '##########################',
       '#########################', '##########################',
       '###########################', '###########################',
       '##########################', '##########################',
       '###########################', '############################',
       '############################', '##########################',
       '###########################', '##########################',
       '##########################', '##########################',
       '##########################', '###########################',
       '############################', '##########################',
       '############################', '##########################',
       '##########################', '###########################',
       '###########################', '############################',
       '############################', '#############################',
       '############################', '############################',
       '#############################', '###########################',
       '#############################', '############################',
       '############################', '#############################',
       '##############################', '#############################',
       '##############################', '#############################',
       '#############################', '##############################',
       '#############################', '############################',
       '##############################', '##############################',
       '##############################', '#############################',
       '##############################', '############################',
       '#############################', '##############################',
       '##############################', '##############################',
       '#############################', '##############################',
       '#############################', '###############################',
       '###############################',
       '###############################',
       '################################',
       '################################',
       '################################',
       '################################',
       '################################',
       '################################',
       '#################################',
       '################################',
       '################################',
       '###############################',
       '################################',
       '###############################',
       '################################',
       '#################################',
       '################################',
       '#################################',
       '##################################',
       '##################################',
       '#################################',
       '#################################',
       '#################################',
       '################################',
       '#################################',
       '##################################',
       '##################################',
       '#################################',
       '#################################',
       '#################################',
       '#################################',
       '##################################',
       '##################################',
       '##################################',
       '#################################',
       '#################################',
       '##################################',
       '##################################',
       '##################################',
       '##################################',
       '##################################',
       '###################################',
       '##################################',
       '##################################',
       '##################################',
       '###################################',
       '###################################',
       '##################################',
       '##################################',
       '##################################',
       '##################################',
       '###################################',
       '####################################',
       '####################################',
       '####################################',
       '#####################################',
       '###################################',
       '###################################',
       '####################################',
       '###################################',
       '####################################',
       '####################################',
       '####################################',
       '####################################',
       '#####################################',
       '###################################',
       '###################################',
       '####################################',
       '####################################',
       '####################################',
       '####################################',
       '#####################################',
       '####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '####################################',
       '####################################',
       '#####################################',
       '#####################################',
       '####################################',
       '#####################################',
       '####################################',
       '#####################################',
       '#####################################',
       '######################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '######################################',
       '######################################',
       '######################################',
       '#####################################',
       '######################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '######################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '######################################',
       '######################################',
       '######################################',
       '######################################',
       '######################################',
       '#####################################',
       '######################################',
       '######################################',
       '######################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '######################################',
       '#####################################',
       '#####################################',
       '######################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '####################################',
       '####################################',
       '####################################',
       '#####################################',
       '#####################################',
       '#####################################',
       '####################################',
       '####################################',
       '####################################',
       '####################################',
       '####################################',
       '####################################',
       '####################################',
       '#####################################',
       '#####################################',
       '####################################',
       '####################################',
       '######################################',
       '#####################################',
       '####################################',
       '####################################',
       '####################################',
       '#####################################',
       '###################################',
       '###################################',
       '###################################',
       '###################################',
       '###################################',
       '###################################',
       '####################################',
       '###################################',
       '###################################',
       '##################################',
       '###################################',
       '###################################',
       '##################################',
       '#################################',
       '####################################',
       '###################################',
       '###################################',
       '##################################',
       '##################################',
       '#################################',
       '##################################',
       '###################################',
       '##################################',
       '##################################',
       '#################################',
       '#################################',
       '#################################',
       '#################################',
       '#################################',
       '################################',
       '################################',
       '################################',
       '#################################',
       '#################################',
       '################################',
       '################################',
       '################################',
       '###############################',
       '###############################',
       '###############################',
       '###############################', '##############################',
       '################################',
       '##############################', '##############################',
       '##############################', '##############################',
       '#############################', '##############################',
       '##############################', '#############################',
       '#############################', '#############################',
       '#############################', '##############################',
       '#############################', '############################',
       '############################', '############################',
       '############################', '############################',
       '###########################', '############################',
       '##########################', '##########################',
       '###########################', '###########################',
       '###########################', '############################',
       '###########################', '###########################',
       '##########################', '##########################',
       '##########################', '#########################',
       '###########################', '##########################',
       '#########################', '#########################',
       '##########################', '#########################',
       '#########################', '#########################',
       '########################', '########################',
       '##########################', '#######################',
       '##########################', '#######################',
       '#########################', '#######################',
       '#######################', '########################',
       '#########################', '#########################',
       '#######################', '#######################',
       '########################', '#########################',
       '#######################', '########################',
       '#######################', '#######################',
       '#######################', '########################',
       '#######################', '########################',
       '######################', '#######################',
       '######################', '#######################'],
      dtype='<U38')

In [124]:
temps.select('Date', 'Highest High').with_column('Highest High Graph', bars).show()